paths:
  /api/products:
    get:
      summary: Obtiene todos los productos de la BD
      tags:
        - Products
      responses:
        "200":
          description: Obtiene todos los productos correctamente
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Product"
        "500":
          description: Error interno del servidor
    post:
      summary: Crea un nuevo producto
      tags:
        - Products
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/requestBodies/createProduct"
      responses:
        "201":
          description: Producto creado correctamente
  /api/products/{pid}:
    get:
      summary: Obtiene un producto por ID
      tags:
        - Products
      parameters:
        - name: pid
          in: path
          required: true
          description: ID del producto a buscar
          schema:
            type: string
      responses:
        "200":
          description: Producto encontrado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"
        "404":
          description: Producto no encontrado
        "500":
          description: Error interno del servidor
    put:
      summary: Actualiza un producto por ID
      tags:
        - Products
      parameters:
        - name: pid
          in: path
          required: true
          description: ID del producto a actualizar
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/requestBodies/updateProduct"
      responses:
        "200":
          description: Producto actualizado correctamente
        "404":
          description: Producto no encontrado
        "500":
          description: Error interno del servidor
    delete:
      summary: Elimina un producto por ID
      tags:
        - Products
      parameters:
        - name: pid
          in: path
          required: true
          description: ID del producto a eliminar
          schema:
            type: string
      responses:
        "204":
          description: Producto eliminado correctamente
        "404":
          description: Producto no encontrado
        "500":
          description: Error interno del servidor

components:
  schemas:
    Product:
      type: object
      properties:
        _id:
          type: string
          description: ID autogenerado por MongoDB
        title:
          type: string
          description: Título del producto
        description:
          type: string
          description: Descripción del producto
        price:
          type: number
          format: float
          description: Precio del producto
        stock:
          type: integer
          description: Stock disponible del producto
        category:
          type: string
          description: Categoría del producto
      example:
        _id: "60d21b4667d0d8992e610c85"
        title: "Producto de ejemplo"
        description: "Descripción del producto de ejemplo"
        price: 99.99
        stock: 10
        category: "Ejemplo"
  requestBodies:
    createProduct:
      type: object
      properties:
        title:
          type: string
          description: Título del producto
        description:
          type: string
          description: Descripción del producto
        price:
          type: number
          format: float
          description: Precio del producto
        stock:
          type: integer
          description: Stock disponible del producto
        category:
          type: string
          description: Categoría del producto
      example:
        title: "Nuevo Producto"
        description: "Descripción del nuevo producto"
        price: 49.99
        stock: 20
        category: "Nueva Categoría"
    updateProduct:
      type: object
      properties:
        title:
          type: string
          description: Título del producto
        description:
          type: string
          description: Descripción del producto
        price:
          type: number
          format: float
          description: Precio del producto
        stock:
          type: integer
          description: Stock disponible del producto
        category:
          type: string
          description: Categoría del producto
      example:
        title: "Producto Actualizado"
        description: "Descripción del producto actualizado"
        price: 59.99
        stock: 30
        category: "Categoría Actualizada"