const EErrors = {
    ROUTING_ERROR: 1,
    INVALID_TYPE_ERROR: 2,
    DATABASE_ERROR: 3,
    INTERNAL_SERVER_ERROR: 4,
    PRODUCT_NOT_FOUND: 5,
    CART_NOT_FOUND: 6,
    PERMISSION_DENIED: 7,
    ADD_PRODUCT_ERROR: 8,
    UPDATE_PRODUCT_ERROR: 9,
    DELETE_PRODUCT_ERROR: 10,
    GET_PRODUCTS_ERROR: 11,
    ADD_TO_CART_ERROR: 12,
    REMOVE_FROM_CART_ERROR: 13,
    UPDATE_PRODUCTS_ERROR: 14,
    UPDATE_QUANTITY_ERROR: 15,
    EMPTY_CART_ERROR: 16,
    PURCHASE_ERROR: 17
};

module.exports = {
    EErrors
};
